catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.apps import CatalogConfig
from catalog.views import ProductListView, ProductDetailView, ProductDeleteView, ProductCreateView, ProductUpdateView, \
    category, BlogListView, BlogCreateView, BlogUpdateView, BlogDetailView, BlogDeleteView, ContactsView

app_name = CatalogConfig.name

urlpatterns = [
    path('create_product/', ProductCreateView.as_view(), name='create_product'),
    path('', ProductListView.as_view(), name='product_list'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('category/', category, name='category'),
    path('product_detail/<int:pk>', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('delete/<int:pk>', cache_page(60)(ProductDeleteView.as_view()), name='delete'),
    path('update_product/<int:pk>', cache_page(60)(ProductUpdateView.as_view()), name='update_product'),
    path('blog/', BlogListView.as_view(), name='blog_list'),
    path('create_blog/', BlogCreateView.as_view(), name='create_blog'),
    path('edit_blog/<int:pk>', BlogUpdateView.as_view(), name='edit'),
    path('view_blog/<int:pk>', BlogDetailView.as_view(), name='view'),
    path('delete_blog/<int:pk>', BlogDeleteView.as_view(), name='delete_blog')

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from users.apps import UsersConfig
from users.forms import StyleFormMixin
from users.views import UserRegistrateView, email_verification, UserPasswordResetView, UserProfileView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name="users/login.html"), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registrate/', UserRegistrateView.as_view(), name='registrate'),
    path('email-confirm/<str:token>/', email_verification, name='email-confirm'),
    path('password_reset/', UserPasswordResetView.as_view(), name='password_reset'),
    path('profile/', UserProfileView.as_view(), name='profile'),
]

catalog/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True, }


class Category(models.Model):
    """Модель описывающая таблицу category в базе данных db_shop"""

    category_name = models.CharField(max_length=50, verbose_name='наименование категории')
    info_category = models.TextField(verbose_name='описание категории', **NULLABLE)

    def __str__(self):
        return f"{self.category_name}"

    class Meta:
        verbose_name = 'категорию'
        verbose_name_plural = 'категорий'
        ordering = ('category_name',)


class Product(models.Model):
    """Модель описывающая таблицу Product в базу данных db_shop"""

    product_name = models.CharField(max_length=50, verbose_name='наименование продукта')
    info_product = models.TextField(verbose_name='описание продукта', **NULLABLE)
    image_product = models.ImageField(upload_to='products/', verbose_name='изображение продукта', **NULLABLE)
    category_product = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='категори продукта',
                                         **NULLABLE, related_name='продукты')
    price = models.IntegerField(verbose_name='цена продукта', **NULLABLE)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='дата последнего изменения', **NULLABLE)

    owner = models.ForeignKey(User, on_delete=models.SET_NULL, verbose_name="пользователь", **NULLABLE)
    is_published = models.BooleanField(default=False, verbose_name="статус публикации продукта")

    def __str__(self):
        return (f"{self.product_name} {self.info_product} {self.category_product}"
                f"{self.price} {self.created_at} {self.updated_at}")

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продуктов'
        ordering = ('-category_product', '-product_name',)
        permissions = [
            ('set_info_product',
             'Can info product'),
            ('set_category_product',
             'Can info product'),
            ('set_published_status',
             'Can published product'),
        ]


class Blog(models.Model):
    """Модуль описывающая таблицу Blog в базе данных db_shop"""
    title = models.CharField(max_length=100, verbose_name='заголовок')
    information = models.TextField(verbose_name='содержание', **NULLABLE)
    preview = models.ImageField(upload_to='blogs/', verbose_name='фото блога', **NULLABLE)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='дата создания')

    slug = models.CharField(max_length=100, verbose_name='slug', **NULLABLE)
    is_published = models.BooleanField(default=True, verbose_name='состояние публикации')
    count_views = models.IntegerField(default=0, verbose_name='количетсво просмотров')

    def __str__(self):
        return f"{self.title}, {self.slug}, {self.information}, {self.is_published}, {self.count_views}"

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блогов'
        ordering = ("-is_published", "-created_at")


class Version(models.Model):
    name_version = models.CharField(max_length=50, verbose_name='название версии')
    number_version = models.IntegerField(verbose_name='номер версии')

    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт')
    is_version = models.BooleanField(verbose_name='состояние версии')

    def __str__(self):
        return f"{self.product}, {self.number_version}, {self.name_version}"

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'
        ordering = ("-is_version",)

catalog/forms.py
from django import forms
from django.forms import BooleanField

from catalog.models import Product, Version, Blog
STOP_LIST = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']


class MixinStyleForm:
    """Класс примесь для стилизации форм продукта"""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs["class"] = "form-check-input"
            else:
                field.widget.attrs["class"] = "form-control"


class ProductForm(MixinStyleForm, forms.ModelForm):
    class Meta:
        model = Product
        exclude = ("created_at", "updated_at", "is_published")

    def clean_product_name(self):
        """Метод проверяющий ввод пользователя на запрещенные слова в наименовании продукта"""
        cleaned_data = self.cleaned_data.get('product_name')

        if cleaned_data.lower() in STOP_LIST:
            raise forms.ValidationError('Ошибка наименования продукта')

        return cleaned_data

    def clean_info_product(self):
        """Метод проверяющий ввод пользователя на запрещенные слова в содержании продукта"""
        cleaned_data = self.cleaned_data.get('info_product')

        for word in STOP_LIST:
            if word in cleaned_data.lower():
                raise forms.ValidationError('Ошибка, в описании продукта содержатся запрещенные слова')

        return cleaned_data


class ProductModeratorForm(MixinStyleForm, forms.ModelForm):
    class Meta:
        model = Product
        fields = ("info_product", "category_product", "is_published")


class VersionForm(MixinStyleForm, forms.ModelForm):
    class Meta:
        model = Version
        fields = '__all__'

    def clean(self):
        """Метод для проверки существования только одной версии продукта"""
        cleaned_data = super().clean()
        current_version = cleaned_data.get("is_version")
        product_version = self.instance.product
        if current_version:
            if Version.objects.filter(product=product_version, is_version=True):
                raise forms.ValidationError("Для продукта может существовать только одна версия")
        return cleaned_data


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = '__all__'

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.forms import inlineformset_factory
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, DeleteView, CreateView, UpdateView, TemplateView

from catalog.forms import ProductForm, VersionForm, ProductModeratorForm
from catalog.models import Product, Blog, Version
from pytils.translit import slugify

from catalog.services import get_categories, get_products


class ProductCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("catalog:product_list")
    permission_required = "catalog.add_product"

    def form_valid(self, form):
        product = form.save()
        product.owner = self.request.user
        product.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    success_url = reverse_lazy("catalog:product_list")

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)

    def get_form_class(self):
        user = self.request.user
        if (user.has_perm("catalog.set_info_product") and user.has_perm("catalog.set_category_product") and
                user.has_perm("catalog.set_published_status")):
            return ProductModeratorForm
        if user == self.object.owner:
            return ProductForm
        raise PermissionDenied


class ProductListView(ListView):
    model = Product

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)
        for product in context_data["object_list"]:
            current_version = Version.objects.filter(product=product, is_version=True)
            product.current_version = current_version
        return context_data

    def form_valid(self, form):
        forms = self.get_context_data()['current_version']
        self.object = form.save()
        if forms.is_valid():
            forms.instance = self.object
            forms.save()

        return super().form_valid(form)

    def get_queryset(self):
        return get_products()


class ProductDetailView(DetailView):
    model = Product


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:product_list')


class BlogFormValidMixin:
    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
            return super().form_valid(form)


class BlogCreateView(BlogFormValidMixin, CreateView):
    model = Blog
    fields = ('title', 'information', 'preview', 'is_published',)
    success_url = reverse_lazy('catalog:blog_list')


class BlogUpdateView(BlogFormValidMixin, UpdateView):
    model = Blog
    fields = ('title', 'information', 'preview', 'is_published',)

    # success_url = reverse_lazy('catalog:blog_list')
    def get_success_url(self):
        return reverse('catalog:view', args=[self.kwargs.get('pk')])


class BlogListView(ListView):
    model = Blog

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.count_views += 1
        self.object.save()
        return self.object


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('catalog:blog_list')


def category(request):
    category_list = get_categories()
    context = {
        'object_list': category_list,
        'title': 'Категории продуктов',
    }
    return render(request, 'catalog/category.html', context)


class ContactsView(TemplateView):
    template_name = "catalog/contacts.html"

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Shop Market</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<header data-bs-theme="dark">
    {% include 'catalog/include/inc_menu.html' %}
</header>
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
    <p class="lead">{{ title_info }}</p>
</div>
<div class="container">
    <div class="row">
        {% block content %}
        {% endblock %}
    </div>
</div>
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            <small class="d-block mb-3 text-muted">&copy; 2024-{% now 'Y' %}</small>
        </div>
        <div class="col-4 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Рассылки</a></li>
                <li><a class="text-muted" href="#">Телеграм боты</a></li>
                <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                <li><a class="text-muted" href="#">Веб-приложения</a></li>
            </ul>
        </div>
        <div class="col-4 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-4 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="{% url 'catalog:contacts' %}">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>

catalog/templates/catalog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <p>Хотите удалить продукт "{{object.title}}"?</p>
                <button type="submit" class="btn btn-block btn-danger">Подтвердить</button>
                <a href="{% url 'catalog:blog_list' %}" class="btn btn-block btn-warning">Отмена</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load tags_and_filters %}
{% block content %}
<div class="col-4">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{ object.title }} ({{ object.slug }})</h4>
        </div>
        <div class="card-body">
            <img src="{{ object.preview | media }}" alt="preview" width="300" height="250"
                 class="d-inline-block align-text-top">
            <h2 class="card-title pricing-card-title">{{ object.slug }}</h2>
            <ul class="list-unstyled mt-3 mb-4 text-center m-3">
                <li>{{ object.information }}</li>
            </ul>
        </div>
        <div class="card-footer">
            Просмотры: {{ object.count_views }}
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/blog_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <form method="post" enctype="multipart/form-data">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/blog_list.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12 mb-5">
    <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'catalog:create_blog' %}">
        Добавить новый блог
    </a>
</div>
{% for object in object_list %}
<div class="col-6" xmlns="http://www.w3.org/1999/html">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
            <p>{{ object.slug }}</p>
        </div>
        <div class="card-body">
            <ul class="list-unstyled mt-3 mb-4 text-center">
                <li>{{ object.information|slice:100 }}</li>
            </ul>
            <div class="btn-group">
                <p class="d-inline-flex gap-1">
                    <a href="{% url 'catalog:view' object.pk %}"
                       class="btn btn-lg btn-block btn-outline-primary">
                        Инфо
                    </a>
                    <a href="{% url 'catalog:edit' object.pk %}"
                       class="btn btn-lg btn-block btn-outline-primary">
                        Обновить
                    </a>
                    {% if user.is_superuser or user.owner %}
                    <a href="{% url 'catalog:delete_blog' object.pk %}"
                       class="btn btn-lg btn-block btn-outline-primary">
                        Удалить
                    </a>
                    {% endif %}
                </p>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

catalog/templates/catalog/category.html
{% extends 'catalog/base.html' %}
{% block content %}
{% for object in object_list %}
<div class="col-3">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <button type="button" class="btn btn-lg btn-block btn-outline-primary">{{ object.category_name }}</button>
        </div>
        <div class="card-body">
            <ul class="list-unstyled mt-3 mb-3 text-center">
                <li>{{ object.info_category|slice:60 }}</li>
            </ul>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>Россия</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>888888008</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Санкт-Петребург, Английская набережная, 9</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="email" class="form-label">Email</label>
                            <input type="email" name='email' class="form-control" id="email"
                                   placeholder="name@example.com">
                        </div>

                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="Сообщение" required></textarea>
                        </div>
                        <button type="submit" value='Отправить' class="btn btn-lg btn-block btn-outline-primary">
                            Отправить
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}
{% block content %}
{% for object in object_list %}
<div class="col-4">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{ object.product_name }}</h4>
        </div>
        <div class="card-body">
            <h2 class="card-title pricing-card-title">{{ object.price }}</h2>
            <ul class="list-unstyled mt-3 mb-4 text-center">
                <li>{{ object.info_product|slice:100 }}</li>
            </ul>
            <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <p>Хотите удалить продукт "{{object.product_name}}"?</p>
                <button type="submit" class="btn btn-block btn-danger">Подтвердить</button>
                <a href="{% url 'catalog:product_list' %}" class="btn btn-block btn-warning">Отмена</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load tags_and_filters %}
{% block content %}
<div class="col-4">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{ object.product_name }}</h4>
        </div>
        <div class="card-body">
            <img src="{{ object.image_product | media }}" alt="image_product" width="300" height="250"
                 class="d-inline-block align-text-top">
            <h2 class="card-title pricing-card-title">{{ object.price }}</h2>
            <ul class="list-unstyled mt-3 mb-4 text-center m-3">
                <li>{{ object.info_product }}</li>
            </ul>
            <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card-header">
                <div class="card-title">
                    <h4>Продукт</h4>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">
                        {% if object %}
                        Cохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </div>
            </div>
            <div class="card-footer"></div>
        </div>
        <div class="col-6">
            <div class="card-header">
                <div class="card-title">
                    <h4>Версия продукта</h4>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                        {{ form.as_p }}
                    {% endfor %}
                </div>
            </div>
            <div class="card-footer"></div>
        </div>
    </form>
</div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12 mb-5">
    {% if perms.catalog.add_product %}
    <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'catalog:create_product' %}">
        Добавить продукт
    </a>
    {% endif %}
</div>
{% for object in object_list %}
<div class="col-6" xmlns="http://www.w3.org/1999/html">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <h4 class="my-0 font-weight-normal">{{ object.product_name }}</h4>
            {% for object in object.current_version%}
            <p>Наименование версии: {{ object.name_version }} Номер версии: {{ object.number_version }}</p>
            {% endfor %}
        </div>
        <div class="card-body">
            <h2 class="card-title pricing-card-title">{{ object.price }}</h2>
            <ul class="list-unstyled mt-3 mb-4 text-center">
                <li>{{ object.info_product|slice:100 }}</li>
            </ul>
            <div class="btn-group">
                <p class="d-inline-flex gap-1">
                    <a href="{% url 'catalog:product_detail' object.pk %}"
                       class="btn btn-lg btn-block btn-outline-primary">
                        Инфо
                    </a>
                    {% if perms.catalog.set_info_product and perms.catalog.set_category_product and perms.catalog.set_published_status or user == object.owner %}
                    <a href="{% url 'catalog:update_product' object.pk %}"
                       class="btn btn-lg btn-block btn-outline-primary">
                        Обновить
                    </a>
                    {% endif %}
                    {% if user.is_superuser or user.owner %}
                    <a href="{% url 'catalog:delete' object.pk %}"
                       class="btn btn-lg btn-block btn-outline-primary">
                        Удалить
                    </a>
                    {% endif %}
                    <a class="btn btn-lg btn-block btn-outline-primary">
                        Купить
                    </a>
                </p>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}